const status = document.querySelector("#status"), file = document.querySelector("#file"), button = document.querySelector("#download");
const params = new URLSearchParams(location.hash.slice(1)), addr = params.get("tc");
let conn, hello, pending = new Uint8Array();
async function readBytes(n) { while (pending.length < n) { const b=await conn.read(); if (!b) throw Error("closed"); const x=new Uint8Array(pending.length+b.length); x.set(pending); x.set(b,pending.length); pending=x; } const out=pending.slice(0,n); pending=pending.slice(n); return out; }
async function readFrame() { const h=await readBytes(4), n=new DataView(h.buffer).getUint32(0); return JSON.parse(new TextDecoder().decode(await readBytes(n))); }
function frame(m) { const b = new TextEncoder().encode(JSON.stringify(m)), o = new Uint8Array(4+b.length); new DataView(o.buffer).setUint32(0,b.length); o.set(b,4); return o; }
async function connect() { if (params.get("v") !== "1" || !addr) { status.textContent="Invalid link"; return; } try { conn=await tailcatDial({addr}); hello=await readFrame(); hello.name=hello.name.replace(/[\\/]/g, "_") || "download"; file.textContent=`${hello.name}\n${(hello.size/1e6).toFixed(1)} MB`; button.hidden=false; status.textContent="Ready to download"; } catch { status.textContent="Could not connect — reload to retry"; } }
button.onclick=async()=>{ button.disabled=true; status.textContent="Downloading…"; try { await conn.write(frame({type:"get"})); let a=[],n=0; while(n<hello.size){const b=await readBytes(Math.min(64*1024,hello.size-n));a.push(b);n+=b.length;} const done=await readFrame(); if(done.type!=="done") throw Error("bad completion"); const blob=new Blob(a,{type:hello.mime||"application/octet-stream"}), link=document.createElement("a"); link.href=URL.createObjectURL(blob); link.download=hello.name; link.click(); status.textContent="Downloaded"; conn.close(); } catch { status.textContent="Download failed"; button.disabled=false; } };
window.onTailcatReady = connect;
